In [162]:
import pandas as pd

In [163]:
df = pd.read_csv('survey_results_public.csv', low_memory = False, encoding = 'utf-8')
df1 = pd.read_csv('survey_results_schema.csv', low_memory = False, encoding = 'utf-8')

In [164]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
df1

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

## Завдання 1. Підрахунок загальної кількості респондентів

In [166]:
count_responseld = df['ResponseId'].nunique()
print (f'В опитуванні взяли участь {count_responseld} респондентів')

В опитуванні взяли участь 49191 респондентів

In [167]:
df['ResponseId'].is_unique #Перевірка на унікальністьреспондентів. Дублікати респондентів відсутні

True

## Завдання 2. Аналіз повноти відповідей респондентів

In [168]:
questions = set(df1['qname']) # список питань df1

df_columns = set(df.columns)
common_questions = questions.intersection(df_columns) # спільні питання df і df1
respondents_full_answers = df.dropna(subset=common_questions) # відповіді на всі питання
count_full_respondents = respondents_full_answers.shape[0] # к-ть респондентів, що відповіли на всі запитання
print (f'{count_full_respondents} респондентів відповіли на всі запитання')

0 респондентів відповіли на всі запитання

 ## Завдання 3. Статистичний аналіз досвіду респондентів

In [188]:
mean_workexp = round(df['WorkExp'].mean(), 1) # Середнє значення (mean)
median_workexp = df['WorkExp'].median() # Медіана (median)
mode_workexp = df['WorkExp'].mode()[0] # Мода (mode)
print (f'Міри центральної тенденції : Середнє значення = {mean_workexp}, Медіана = {median_workexp}, Мода = {mode_workexp}')
# Висновок: 
# Медіана = 10 р досвіду, що свідчить про те, що половина респондентів має досвід роботи менше або дорівнює 10 років.
# Мода = 10 р досвіду, що свідчить про те, найбільше респондентів має досвід роботи 10 років.
# Середнє значення = 13,4 р досвіду. Сережнє значення більше за медіану, це вказує на респонедентів з великим досвідом, які тягнуть середнє вгору.

Міри центральної тенденції : Середнє значення = 13.4, Медіана = 10.0, Мода = 10.0

## Завдання 4. Аналіз віддаленої роботи

In [170]:
count_remote = (df['RemoteWork'] == 'Remote').sum()
print (f'{count_remote} респондентів працюють віддалено')

10931 респондентів працюють віддалено

 ## Завдання 5. Визначення популярності Python

In [191]:
worked_with_python = df['LanguageHaveWorkedWith'].str.contains('Python', na = False).sum() # Кількість респондентів, які програмують на Python
python_percent = round((worked_with_python / count_responseld) * 100 , 1)
print (f'Відсоток респондентів, які програмують на Python: {python_percent} %')

Відсоток респондентів, які програмують на Python: 37.5 %

 ## Завдання 6. Аналіз шляхів навчання програмуванню

In [172]:
Learned_with_online_course = df['LearnCode'].str.contains('Online Courses', na = False).sum()
print (f'{Learned_with_online_course} респондентів навчалося програмувати за допомогою онлайн курсів')

10973 респондентів навчалося програмувати за допомогою онлайн курсів

 ## Завдання 7. Географічний аналіз компенсації Python-розробників

In [173]:
worked_with_python = df[df['LanguageHaveWorkedWith'].str.contains('Python', na = False)]
worked_with_python = worked_with_python.dropna(subset = ['ConvertedCompYearly', 'Country']) # видалення відсутніх значень комепенсації
grouped_by_country = worked_with_python.groupby('Country') # групування за країнами
mean_compensation = round(grouped_by_country['ConvertedCompYearly'].mean(), 2) # середнє
median_compensation = round(grouped_by_country['ConvertedCompYearly'].median(), 2) # медіана
py_progres_by_country = pd.DataFrame({
    'mean_compensation': mean_compensation,
    'median_compensation': median_compensation
})
py_progres_by_country

                                      mean_compensation  median_compensation
Country
Afghanistan                                    22328.67               1000.0
Albania                                        47217.60              50000.0
Algeria                                        20187.29               7088.0
Andorra                                       226103.50             226103.5
Antigua and Barbuda                                1.00                  1.0
...                                                 ...                  ...
Venezuela, Bolivarian Republic of...            9908.65               3000.0
Viet Nam                                      218837.17               8254.0
Yemen                                          32929.50              23672.0
Zambia                                          5424.25               3206.0
Zimbabwe                                       34000.00              25500.0

[153 rows x 2 columns]

## Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [174]:
df_sort_comp = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]
df_sort_comp = df_sort_comp.dropna(subset = ['ConvertedCompYearly']) # видалення відсутніх значень
df_sort_comp = df_sort_comp.sort_values('ConvertedCompYearly', ascending = False) # сортування за спаданням
df_sort_comp = df_sort_comp.reset_index(drop = True) # оновлення індексів
top5 = df_sort_comp.head(5)
top5

# Висновок: Річна компенсація не залежить лише від рівня освіти. 
# Перше місце займає респондент з hsdytv освіти Associate degree, а друге - роспондент з Master’s degree.

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

## *Завдання 9. Аналіз популярності Python по віковим категоріям

In [178]:
df['Python'] = df['LanguageHaveWorkedWith'].str.contains('Python', na = False)
df_age = df.dropna(subset = ['Age']) # видалення відсутніх значень віку для респондентів
python_count = df_age[df_age['Python'] == True].groupby('Age')['Python'].sum() # к-ть респондентів, що програмують на python у кожній віковій групі, 
total_count = df_age.groupby('Age')['Python'].count() # загальна к-ть респондентів у кожній віковій групі
python_percent_group_age = round((python_count / total_count) * 100, 2) # % Python-розробників по віковим групам
python_percent_group_age = pd.DataFrame({'% Python-розробників': python_percent_group_age})
python_percent_group_age

# Висновок: Найбільше Python-розробників у віковій групі 18-24 роки, а найменше - 65 і більше років.

                   % Python-розробників
Age
18-24 years old                   40.00
25-34 years old                   36.94
35-44 years old                   36.72
45-54 years old                   38.63
55-64 years old                   37.24
65 years or older                 31.63
Prefer not to say                 31.22

## *Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [179]:
Q3 = df['ConvertedCompYearly'].quantile(0.75) #75-й перцентиль:
high_paid_remote = df[
    (df['ConvertedCompYearly'] >= Q3) &
    (df['RemoteWork'] == 'Remote')] # Респонденти, які заробляють більше, ніж 75% респондентів і працюють віддалено
industry_counts = high_paid_remote['Industry'].value_counts()
industry_counts

# Висновок: Найрозповсюдженіші індустрі: Software Development - 1186, Fintech - 190, Healthcare - 188.

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64